##### Convert from hourly data to desired timescales for precipitation #####

#**# Watch processing of leap-years

setwd(data.dir)

# Loop through scenarios
for (timestep in timesteps){

  # For each variable, process it at each time scale
  #for (var in precip.vars){
  var = "RAINNC"
  
  main.var = sprintf("%s_%s", var, timestep)
  
  # Loop through years
  for (i in (first.year):(last.year)){
    
    
    message(sprintf("Processing %s for year %s", main.var, i))
    
    is.leap = 0
    if (i %in% leap.years){  is.leap = 1  }

    if ('daily' %in% timescales){
      # Read in this year's data for main variable
      in.file = sprintf("Vars/%s/%s/AnnualHourly/%s_year_%s_%s.rda",island, main.var, main.var, i, TimeZone.Label)
      load(in.file)
      rainnc = new.var
      rm(new.var)
      
      # Create a table with daily precipitation
      initial.value = NA
      daily.stuff = create.daily.ppt.files(i, var, rainnc, timestep, island)
    }

    # Make sure there is a daily file to use if daily timestep is not selected.
    if (!'daily' %in% timescales ){
      daily.file = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s.rda",island, var, timestep, var, timestep, i + 1989)
      if (!file.exists(daily.file)){
        stop(sprintf("%s file not found, this file must exist to process the mean annual precipitation and can be generated by including 'daily' in the timescales variable", daily.file)) 
      }
      load(daily.file) # loads the day.ppt.array object
      daily.stuff = day.ppt.array
      rm(day.ppt.array)
    }
    
    # Process it to each timescale
    
    # Monthly should just be the sum of the time slice associated with a particular month
    if ("monthly" %in% timescales){
      calculate.mean.monthly.ppt(daily.stuff, i, var, timestep, is.leap, island)
    }
    
    # Annual should just be the average of the entire ncdf file
    if ("annual" %in% timescales){
      #year.path = sprintf("Vars/%s/%s_%s/AnnualPPT/AnnualPPT_%s_%s_year_%s.rda", island, var, timestep, var, timestep, i + 1989)
      calculate.mean.annual.ppt(daily.stuff, i, var, timestep, is.leap, island)
    }
  }
  
  # Create climatologies
  if ("monthly" %in% timescales){
    calculate.monthly.climatologies(first.year, last.year, var, timestep, island)
  }
  if ('annual' %in% timescales){
    calculate.annual.climatologies(first.year, last.year, var, timestep, island)
  }
}
