---
title: "Rainfall Explorer"
author: "A.C. Keyel"
date: "8/13/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Set up R scenarios for extracted data

```{r oahu_setup, include=TRUE}
island = "oahu"
setwd("C:/hawaii_local/Vars/oahu")
TimeZone.Label = "GMT-10"
var = "RAIN"
i = 2 # look at 2nd year, to avoid any oddities associated with spin-up
timestep = 'present'

main.var = sprintf("%s_%s", var, timestep)
other.var = sprintf("%sNC_%s", var, timestep)

# Read in this year's data for main variable
load(sprintf("%s/AnnualHourly/%s_year_%s_%s.rda",main.var, main.var, i, TimeZone.Label))
rain = new.var
rm(new.var)
      
# Read in this year's data for the secondary variable
load(sprintf("%s/AnnualHourly/%s_year_%s_%s.rda",other.var, other.var, i, TimeZone.Label))
# Loads the new.var object
rainnc = new.var
rm(new.var)

load(sprintf("I_RAINNC/AnnualHourly/I_RAINNC_year_%s_%s.rda", i, TimeZone.Label))
irainnc = new.var
rm(new.var)

irain

# Set up lat/lon for the 3 locations
loc.lats = c(13, 43, 42)
loc.lons = c(54, 58, 52)

```

## Select 3 locations to give context
(75, 97 are maximum index values)
13, 54 is Honolulu 
43, 58 is on NE side of mountains on the island
42, 52 is on the SW side of the mountains (but still near the NE coast)

## Explore basic plots
```{r basic_plots, include=FALSE}

par(mfrow = c(3,1))

for (j in 1:3){
  lat = loc.lats[j]
  lon = loc.lons[j]
  
  plot(rainnc[lat, lon, 1:8670])
  
}


```

```{r junk, include=FALSE}

      
      is.leap = 0
      #**# NEED CONTROL TO CHANGE TO LEAP YEAR DEPENDING ON VALUES OF i
      
      plot(rainnc[45,45,])

      #**# NEEDS DIFFERENT PROCESSING FOR PRECIP      
      # Create a table with daily tmin, tmax, tmean
      #day.start = 11 #**# CONFIRM WITH OLIVER AND RYAN ABOUT THIS!
      #daily.stuff = create.daily.files(i, var, leap.years, new.var, day.start)
      
      # Process it to each timescale
      
      # Monthly should just be the sum of the time slice associated with a particular month
      #**# FIX
      #if ("monthly" %in% timescales){
      #  calculate.min.max.mean.monthly(daily.stuff, i, var) # Creates a file names XXXX
      #}
      
      # Annual should just be the average of the entire ncdf file
      #**# FIX
      #if ("annual" %in% timescales){
      #  calculate.min.max.mean.annual(daily.stuff, i, var)
      #}
#    }
#  }
#}
```
