##### Convert from hourly data to desired timescales for precipitation #####

#**# Watch processing of leap-years

setwd(data.dir)

# Loop through scenarios
for (timestep in timesteps){

  # Loop through years
  for (i in first.year:last.year){
    
    for (j in 1:3){
      # For each variable, process it at each time scale
      #for (var in precip.vars){
      var = "RAINNC"
      
      main.var = sprintf("%s_%s", var, timestep)
      
      message(sprintf("Processing %s for year %s part %s", main.var, i, j))
      
      is.leap = 0
      if (i %in% leap.years){  is.leap = 1  }
      
      if ('part' %in% timescales){
        # Read in this year's data for main variable
        in.file = sprintf("Vars/%s/%s/AnnualHourly/%s_year_%s_%s_%s.rda",island, main.var, main.var, i, j, TimeZone.Label)
        load(in.file)
        rainnc = new.var
        rm(new.var)
        
        # Create a table with daily precipitation
        initial.value = NA
        part.stuff = create.daily.ppt.files(i, var, rainnc, timestep, island, j)
      }

    }
    

    if ('daily' %in% timescales){
      #**# NEED TO PATCH THE THREE PART FILES TOGETHER. REQUIRES REMEMBERING HOW TO CORRECTLY MERGE ARRAYS
      # Read in this year's data for main variable
      in.file1 = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s_part_%s.rda",island, var, timestep, var, timestep, i + 1989, 1)
      load(in.file1)
      part1 = day.ppt.array
      rm(day.ppt.array)
      part1.dims = dim(part1)
      # Load FILE 2
      in.file2 = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s_part_%s.rda",island, var, timestep, var, timestep, i + 1989, 2)
      load(in.file2)
      part2 = day.ppt.array
      rm(day.ppt.array)
      part2.dims = dim(part2)

      # Load FILE 3
      in.file3 = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s_part_%s.rda",island, var, timestep, var, timestep, i + 1989, 3)
      load(in.file3)
      part3 = day.ppt.array
      rm(day.ppt.array)
      part3.dims = dim(part3)

      # MERGE ARRAY
      long = part1.dims[1] #**# CHECK THIS IS THE RIGHT DIMENSION!!!
      lat = part1.dims[2]
      total.dim = part1.dims[3] + part2.dims[3] + part3.dims[3] #lat/long should be the same for all three arrays. 
      day.ppt.array = array(c(part1, part2, part3), dim = c(long, lat, total.dim))
      #**# Check that this worked correctly
      
      # SAVE AS DAILY FILE
      daily.file = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s.rda",island, var, timestep, var, timestep, i)
      save(day.ppt.array, file = daily.file)
      
    }
    
    # Make sure there is a daily file to use if daily timestep is not selected.
    if (!'daily' %in% timescales ){
      daily.file = sprintf("Vars/%s/%s_%s/DailyPPT/DailyPPT_%s_%s_year_%s.rda",island, var, timestep, var, timestep, i)
      if (!file.exists(daily.file)){
        stop(sprintf("%s file not found, this file must exist to process the mean annual precipitation and can be generated by including 'daily' in the timescales variable", daily.file)) 
      }
      load(daily.file) # loads the day.ppt.array object
      #daily.stuff = day.ppt.array
      #rm(day.ppt.array)
    }
    
    # Monthly should just be the sum of the time slice associated with a particular month
    if ("monthly" %in% timescales){
      #calculate.mean.monthly.ppt(daily.stuff, i, var, timestep, is.leap, island)
      calculate.mean.monthly.ppt(day.ppt.array, i, var, timestep, is.leap, island)
    }
    
    # Annual should just be the average of the entire ncdf file
    if ("annual" %in% timescales){
      #year.path = sprintf("Vars/%s/%s_%s/AnnualPPT/AnnualPPT_%s_%s_year_%s.rda", island, var, timestep, var, timestep, i + 1989)
      #calculate.mean.annual.ppt(daily.stuff, i, var, timestep, is.leap, island)
      calculate.mean.annual.ppt(day.ppt.array, i, var, timestep, is.leap, island)
    }
  }
  
  # Create climatologies
  if ("monthly" %in% timescales){
    calculate.monthly.climatologies(first.year + 1989, last.year + 1989, var, timestep, island)
  }
  if ('annual' %in% timescales){
    calculate.annual.climatologies(first.year + 1989, last.year + 1989, var, timestep, island)
  }
}